### ISSUE TITLE
No support for ED25519 keys (replace JSCH library)

### ISSUE THREAD

**Issue by sratz** [sonyxperiadev/gerrit-events#113]
gerrit-events does not support ED25519 keys:

```
	com.sonymobile.tools.gerrit.gerritevents.ssh.SshException: com.jcraft.jsch.JSchException: invalid privatekey: [B@5e887fa3
		at com.sonymobile.tools.gerrit.gerritevents.ssh.SshConnectionImpl.connect(SshConnectionImpl.java:200)
		at com.sonymobile.tools.gerrit.gerritevents.ssh.SshConnectionFactory.getConnection(SshConnectionFactory.java:140)
		at com.sonymobile.tools.gerrit.gerritevents.ssh.SshConnectionFactory.getConnection(SshConnectionFactory.java:117)
		at com.sonymobile.tools.gerrit.gerritevents.GerritConnection.connect(GerritConnection.java:498)
		at com.sonymobile.tools.gerrit.gerritevents.GerritConnection.run(GerritConnection.java:404)
	Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@5e887fa3
		at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
		at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
		at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
		at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
		at com.jcraft.jsch.JSch.addIdentity(JSch.java:387)
		at com.sonymobile.tools.gerrit.gerritevents.ssh.SshConnectionImpl.connect(SshConnectionImpl.java:168)
		... 4 more
```

This is because the JSCH library does not.

Since JSCH seems not to be maintained anymore, it should be considered to switch to an alternative SSH library, e.g. Apache MINA.

**Comment by Apteryks** [comment]
Cross-linking to the Gerrit Trigger issue: https://issues.jenkins.io/browse/JENKINS-67563.

**Comment by rsandell** [comment]
Sure, Apache MINA is already used in test scope. Though it might cause some issues in runtime due to a core dependency on the same library.

**Comment by sratz** [comment]
Any update on this matter?
@rsandell: Could we maybe get #120 or #125 merged?
