### ISSUE TITLE
Objects in package com.sonymobile.tools.gerrit.gerritevents.dto.events should have a Constructor with JSONObject as parameter

### ISSUE THREAD

**Issue by longwusha** [sonyxperiadev/gerrit-events#65]
[2017-07-12 13:31:51 DEBUG] [Gerrit Worker EventThread_1] {com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory:73}-Constructor with JSONObject as parameter missing, trying default constructor.
java.lang.NoSuchMethodException: com.sonymobile.tools.gerrit.gerritevents.dto.events.CommentAdded.<init>(net.sf.json.JSONObject)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory.getEvent(GerritJsonEventFactory.java:69)
	at com.sonymobile.tools.gerrit.gerritevents.workers.AbstractJsonObjectWork.perform(AbstractJsonObjectWork.java:69)
	at com.sonymobile.tools.gerrit.gerritevents.workers.StreamEventsStringWork.perform(StreamEventsStringWork.java:67)
	at com.sonymobile.tools.gerrit.gerritevents.workers.EventThread.run(EventThread.java:66)

As you can see,because of the missing of Constructor with JSONObject as parameter,it will throw a lot of java.lang.NoSuchMethodException.

I am not sure the listener will work correctly in this case.But it make us confuse.

I hope someone can fix this.Of course,if I have time,I will try to do it as well.

e.....I hope that my poor english will not confuse you.I am a chinese.

**Comment by rsandell** [comment]
But it doesn't complain about the default constructor from what I can see, so you should be safe.

**Comment by rinrinne** [comment]
Why are you setting log level to DEBUG?

**Comment by Meteor-lws** [comment]
@rsandell 
may be it is safe,but a better choice is to fix this problem

**Comment by Meteor-lws** [comment]
@rinrinne 
because i want to see some more detail message of mybatis

**Comment by liliVicky** [comment]
20:21:33.091 [Gerrit Worker EventThread_2] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - Trying default constructor.
20:21:33.090 [Gerrit Worker EventThread_3] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - Parsed a JSONObject
20:21:33.091 [Gerrit Worker EventThread_3] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - Type found: REVIEWER_ADDED
20:21:33.091 [Gerrit Worker EventThread_3] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - It is interesting and usable.
20:21:33.091 [Gerrit Worker EventThread_3] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - Interesting event with a class defined. Searching shorthand constructor.
20:21:33.092 [Gerrit Worker EventThread_3] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - Constructor with JSONObject as parameter missing, trying default constructor.
java.lang.NoSuchMethodException: com.sonymobile.tools.gerrit.gerritevents.dto.events.ReviewerAdded.<init>(net.sf.json.JSONObject)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory.getEvent(GerritJsonEventFactory.java:69)
	at com.sonymobile.tools.gerrit.gerritevents.workers.AbstractJsonObjectWork.perform(AbstractJsonObjectWork.java:69)
	at com.sonymobile.tools.gerrit.gerritevents.workers.StreamEventsStringWork.perform(StreamEventsStringWork.java:67)
	at com.sonymobile.tools.gerrit.gerritevents.GerritHandler$EventWorker.run(GerritHandler.java:302)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:21:33.091 [Gerrit Worker EventThread_2] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - Returning an event: com.sonymobile.tools.gerrit.gerritevents.dto.events.CommentAdded@14512775
20:21:33.092 [Gerrit Worker EventThread_2] DEBUG com.sonymobile.tools.gerrit.gerritevents.workers.AbstractJsonObjectWork - Event is: com.sonymobile.tools.gerrit.gerritevents.dto.events.CommentAdded@14512775
20:21:33.092 [Gerrit Worker EventThread_3] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritJsonEventFactory - Trying default constructor.
20:21:33.092 [Gerrit Worker EventThread_2] DEBUG com.sonymobile.tools.gerrit.gerritevents.GerritHandler - No apropriate method found during reflection. Calling default.
java.lang.NoSuchMethodException: com.huawei.gerrit.MyEventListener.gerritEvent(com.sonymobile.tools.gerrit.gerritevents.dto.events.CommentAdded)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.sonymobile.tools.gerrit.gerritevents.GerritHandler.notifyListener(GerritHandler.java:495)
	at com.sonymobile.tools.gerrit.gerritevents.GerritHandler.notifyListeners(GerritHandler.java:476)
	at com.sonymobile.tools.gerrit.gerritevents.workers.AbstractGerritEventWork.perform(AbstractGerritEventWork.java:46)
	at com.sonymobile.tools.gerrit.gerritevents.workers.AbstractJsonObjectWork.perform(AbstractJsonObjectWork.java:77)
	at com.sonymobile.tools.gerrit.gerritevents.workers.StreamEventsStringWork.perform(StreamEventsStringWork.java:67)
	at com.sonymobile.tools.gerrit.gerritevents.GerritHandler$EventWorker.run(GerritHandler.java:302)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


===========================

I got the same problem, I don't know why

**Comment by rsandell** [comment]
There is no problem, if there was it would have been logged as at a SEVERE level. It's just a debug message that it didn't find a shorthand constructor and will go with the default constructor + the parse method.
